events {}

http {

    server {

        listen 80;

        location / {
            proxy_pass http://result/;
        }

        location /vote/ {
            proxy_pass http://vote/;

            sub_filter_once off;
            sub_filter_types text/html;

            sub_filter 'href="/static/' 'href="/vote/static/';
            sub_filter 'action="/"' 'action="/vote/"';
        }
    }
}