server {

    listen 80;
    server_name vote.sumayyasayeed.online localhost;

    location / {

        proxy_pass http://result;

        include /etc/nginx/snippets/proxy.conf;
    }

    location /vote/ {

        proxy_pass http://vote/;

        include /etc/nginx/snippets/proxy.conf;

        sub_filter_once off;
        sub_filter_types text/html;

        sub_filter 'href="/static/' 'href="/vote/static/';
        sub_filter 'action="/"' 'action="/vote/"';
    }

}