name: Build Vote

on:
  push:
    branches:
      - main
    paths:
      - 'vote/**'
      - 'docker-compose.yml'
      - '.github/workflows/build-service.yml'
      - '.github/workflows/build-vote.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'vote/**'
      - 'docker-compose.yml'
      - '.github/workflows/build-service.yml'
      - '.github/workflows/build-vote.yaml'
permissions:
  id-token: write
  contents: read
jobs:
  build:
    uses: ./.github/workflows/build-service.yml

    with:
      service: vote

    secrets: inherit