name: OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check OIDC Token Availability
        run: |
          if [ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ]; then
            echo "❌ OIDC URL NOT AVAILABLE"
          else
            echo "✅ OIDC URL AVAILABLE"
          fi

          if [ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
            echo "❌ OIDC TOKEN NOT AVAILABLE"
          else
            echo "✅ OIDC TOKEN AVAILABLE"
          fi
      - name: Dump OIDC Claims
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const token = await core.getIDToken('sts.amazonaws.com');

            const payload = JSON.parse(
              Buffer.from(token.split('.')[1], 'base64').toString()
            );

            console.log(JSON.stringify(payload, null, 2));

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168415108:role/GithubActionRole
          aws-region: ap-south-1

      - run: aws sts get-caller-identity