name: Docker CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  docker-build:

    name: Build Docker Application

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v7