name: Deploy to EC2

on:

  workflow_call:

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: votingappbucket9876

jobs:

  ec2-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Create Deployment Archive
        run: |
          tar -czf deployment.tar.gz \
            docker-compose.yml \
            nginx \
            ec2deploy.sh

      - name: Upload Deployment Bundle
        run: |
          aws s3 cp deployment.tar.gz \
            s3://${{ env.S3_BUCKET }}/deployment/latest/deployment.tar.gz
      - name: Trigger Deployment
      # AWS-RunShellScript is an AWS Systems Manager Document (SSM Document).
        run: |

          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Project,Values=example-voting-app" \
          --parameters 'commands=[
          "echo '=== Starting Download ===' > /tmp/deploy.log",
          "date >> /tmp/deploy.log",
          "aws s3 cp s3://${{ env.S3_BUCKET }}/deployment/latest/deployment.tar.gz /tmp/deployment.tar.gz >> /tmp/deploy.log 2>&1",
          "echo 'Exit Code:' $? >> /tmp/deploy.log",
          "ls -lh /tmp >> /tmp/deploy.log 2>&1",
          "cat /tmp/deploy.log",
          "sudo mkdir -p /opt/votingapp" >> /tmp/deploy.log 2>&1",
          "sudo tar -xzf /tmp/deployment.tar.gz -C /opt/votingapp" >> /tmp/deploy.log 2>&1",
          "sudo /opt/votingapp/ec2deploy.sh >> /tmp/deploy.log 2>&1",
          "ls -lh /tmp >> /tmp/deploy.log 2>&1"
          ]' 