name: Deploy to EC2

on:

  workflow_call:

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  AWS_REGION: ap-south-1
  S3_BUCKET: votingappbucket9876

jobs:

  ec2-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Create Deployment Archive
        run: |
          tar -czf deployment.tar.gz \
            docker-compose.yml \
            nginx \
            ec2deploy.sh

      - name: Upload Deployment Bundle
        run: |
          aws s3 cp deployment.tar.gz \
            s3://${{ env.S3_BUCKET }}/deployment/latest/deployment.tar.gz
      - name: Trigger Deployment
      # AWS-RunShellScript is an AWS Systems Manager Document (SSM Document).
        run: |

          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Project,Values=example-voting-app" \
          --parameters '{
            "commands": [
              "echo \"=== Starting Download ===\" > /tmp/deploy.log",
              "aws s3 cp s3://${{ env.S3_BUCKET }}/deployment/latest/deployment.tar.gz /tmp/deployment.tar.gz >> /tmp/deploy.log 2>&1",
              "mkdir -p /opt/votingapp >> /tmp/deploy.log 2>&1",
              "tar -xzf /tmp/deployment.tar.gz -C /opt/votingapp >> /tmp/deploy.log 2>&1",
              "export DOCKERHUB_USERNAME=${{ env.DOCKERHUB_USERNAME }} >> /tmp/deploy.log 2>&1",
              "chmod +x /opt/votingapp/ec2deploy.sh",
              "/opt/votingapp/ec2deploy.sh >> /tmp/deploy.log 2>&1"
            ]
          }'